services:
  eks-cui:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - eks-aws-config:/root/.aws
      - eks-kube-config:/root/.kube
      - .:/workspace
      - /dev/shm:/dev/shm  # Chrome用共有メモリ
    environment:
      - AWS_PAGER=
      - CLUSTER_NAME=${CLUSTER_NAME}
      - REGION=${REGION}
      - ROLE_ARN=${ROLE_ARN}
      - DISPLAY=:99
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - HOME=/root
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  eks-aws-config:
    external: true
  eks-kube-config:
    name: eks-kube-config
